apiVersion: v2
name: candidates
description: HireFlow - Candidates API
type: application
version: 0.1.0
appVersion: "local"
dependencies:
  - name: hf-base
    version: 0.1.0
    repository: "file://../hf-base"
