# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hireflow
  namespace: hireflow
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  rules:
  - host: hireflow.localtest.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gateway
            port: { number: 80 }
