image:
  repository: hireflow/company-jobs
  tag: local
  pullPolicy: IfNotPresent

# NEW: migrator image (separate from API)
migrator:
  image:
    repository: hireflow/company-jobs-migrator
    tag: local
    pullPolicy: IfNotPresent

db:
  connectionStringKey: SqlServer   # <-- reuse existing key for now

replicaCount: 2

fullnameOverride: company-jobs

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  ASPNETCORE_URLS: "http://0.0.0.0:8080"

secretRefName: "hireflow-connections"

ingress:
  enabled: false
  className: nginx
  host: hireflow.localtest.me
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
  path: /
  pathType: Prefix

resources:
  requests: { cpu: 100m, memory: 128Mi }
  limits:   { cpu: 500m, memory: 512Mi }