apiVersion: v2
name: notifications
description: HireFlow - Notifications worker
type: application
version: 0.1.0
appVersion: "local"
dependencies:
  - name: hf-base
    version: 0.1.0
    repository: "file://../hf-base"
