apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hf.fullname" . }}
  labels:
    {{- include "hf.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hf.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hf.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "hf.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.service.targetPort }}
            name: http
        envFrom:
          - secretRef:
              name: {{ .Values.secretRefName }}
        env:
          {{- range $k, $v := .Values.env }}
          - name: {{ $k }}
            value: "{{ $v }}"
          {{- end }}
          - name: COMPANYJOBS_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretRefName }}
                key: {{ .Values.db.connectionStringKey | default "SqlServer" }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
