apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hf.fullname" . }}-migrate
  labels:
{{ include "hf.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
{{ include "hf.labels" . | indent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: migrator
          image: "{{ .Values.migrator.image.repository }}:{{ .Values.migrator.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.migrator.image.pullPolicy | default "IfNotPresent" }}
          env:
            - name: COMPANYJOBS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefName }}
                  key: {{ .Values.db.connectionStringKey | default "SqlServer" }}
